###
POST http://localhost:3005/users/
content-type: application/json

{
    "username": "thebled23",
    "password": "wherethebodygoes"
}

###
GET http://localhost:3005/users/

###
PATCH http://localhost:3005/users/

###
DELETE http://localhost:3005/users/