###
POST http://localhost:3005/users/
content-type: application/json

{
    "username": "staticdress34",
    "password": "red_wedding"
}

###
GET http://localhost:3005/users?username=thebled23

###
PATCH http://localhost:3005/users/
content-type: application/json

{
    "username": "thebled23",
    "newPassword": "youknowhosseatbelt"
}
###
DELETE http://localhost:3005/users/
content-type: application/json

{
    "username": "thebled23"
}